### ISSUE TITLE
add pipeline specific fields

### ISSUE THREAD

**Issue by gdesmott** [standard-ai/tracing-gstreamer#14]
I'd like to be able to add custom fields to specific gst pipelines. This would help applications running lots of pipelines to get more context from gst logs, do filtering, etc.

My plan was something like this:
- add API adding fields for a given pipeline, something like `tracing_gstreamer::add_field(&pipeline, "custom-field", "custom-value");`  (using pipelines here but another bin or gst element could do as well).
- internally store this field in a map indexed by the `pipeline` pointer
- when handling logs from gst lookup the gobject parents checking if there is custom field(s) associated with it from this map.
- if there is add those to the tracing `Event`

Unfortunately, as I understand [looking at this code](https://github.com/standard-ai/tracing-gstreamer/blob/main/src/callsite.rs#L115), the metadata (and so the fields) need to be static, so I'm not sure how to implement all that.

Any suggestion?

cc @sdroege : this is the plan we discussed few weeks ago.

**Comment by nagisa** [comment]
Hm, even if we were to add a pipeline->metadata mapping, I suspect that getting from an arbitrary object (pad, element) to its owning pipeline has a potential to be pretty expensive (I don't think there's a generic O(1) way to go from a `GstObject` to its owning `GstPipeline`, is there?), and may sometimes be impossible (for e.g. buffers?)

I wonder if it would be possible to instead add custom “properties” with a well-known prefix? If there is a mechanism that allows something like this, we could add a helper method that goes through children to propagate these properties. This way the object tree walk would be a one-time cost (although it wouldn’t transparently handle dynamic pipelines.)

> Unfortunately, as I understand [looking at this code](https://github.com/standard-ai/tracing-gstreamer/blob/main/src/callsite.rs#L115), the metadata (and so the fields) need to be static, so I'm not sure how to implement all that.

Only the field keys need to be static, the field values are dynamic. See callers of `DynamicCallsites::callsite_for` for how this works. In short: this library will leak “metadata” for every unique combination of arguments to this function, which should be a well-bounded quantity (all of the arguments are determined by the log location).

If you can live with something like `custom={json}` or somesuch representation, then it can be made to work alright. Otherwise we’d need to find a way to give end users control of what gets passed as the field argument (which can also be worked around with some `leak`ing, given that people probably can tell at compile time which kinds of fields they would like to see)

**Comment by gdesmott** [comment]
> I don't think there's a generic O(1) way to go from a `GstObject` to its owning `GstPipeline`, is there?

There is not, we have to iterate over object's parents. That may indeed be expensive if we do that for each log message, especially as `gst_object_get_parent()` get the object lock.

> and may sometimes be impossible (for e.g. buffers?)

I wouldn't worry about this much. Objects associated with logs are usually elements or pads, I think that's enough if this new feature supports only those.

> I wonder if it would be possible to instead add custom “properties” with a well-known prefix? If there is a mechanism that allows something like this, we could add a helper method that goes through children to propagate these properties. This way the object tree walk would be a one-time cost

Doing the lookup one time and then caching the field(s) make sense, I think. Fields are not expected to change much as they are meant to provide extra context about the pipeline and its elements.

But I don't understand why you'd need extra properties here rather than just passing fields directly when calling the `tracing-gstreamer` API?

> (although it wouldn’t transparently handle dynamic pipelines.)

Maybe we could watch the pipeline/bin `deep-element-added/removed` and update the cache accordingly?

> If you can live with something like `custom={json}` or somesuch representation, then it can be made to work alright.

I'd rather have a way to be able to use any key/value fields. It would be easier to handle with Grafana Loki as I'd like to use those field to do filtering when displaying logs, etc.

**Comment by nagisa** [comment]
So, I’ve just (re-)realized – `tracing` *has* a mechanism for introducing context. That’s spans.

If we can use these spans somehow in the final solution, we don’t need to think about how to provide an ability to introduce a `'static` field, or walking the stack of GstObject parents all the time or maintaining a cache of these. All we need to provide is an ability for the users to provide their custom root `span!(...)` and to somehow make sure that it is entered at the root of the span/log stack for all the threads that are processing GStreamer objects for a particular `GstPipeline`[^1]. I feel like such `tracing` oriented solution would be much more surmountable than trying to hack away at the GStreamer side of the equation here.

[^1]: We could still maintain a `HashMap<Weak<GstPipeline>, Span>`, I guess, though I wouldn’t be surprised if there's a solution that does not require doing something like that.

Afterwards tracing is able to walk the span stack and include the fields from parent spans into an event by itself. I’m not sure which subscriber you're using with Loki, but https://github.com/tokio-rs/tracing/pull/1299 suggests a fairly minimal layer can be added to the user code to implement the semantics of merging fields from parent spans into the event.

**Comment by gdesmott** [comment]
> So, I’ve just (re-)realized – `tracing` _has_ a mechanism for introducing context. That’s spans.

That's a **very** good point ! :D

I did some experiments and I think I'm getting somewhere.

I'm still not sure what would be the proper way to map pipelines (or any `GstObject`)  with spans here. I can think of two options:
- use GObject's data with a well-known key name (like `tracing-span`) to store the `Span` object.
- add some API like `tracing_gstreamer::add_span(object: &gstreamer::Object, span: tracing::Span)`

I think I prefer the latter as it's less magic and more discoverable when looking at the crate documentation but that would require adding this `HashMap<Weak<GstPipeline>, Span>`.

What do you think?

> walking the stack of GstObject parents all the time

We'd still need to walk the parents with my solution (modulo some caching maybe). How would you get rid of that?

**Comment by nagisa** [comment]
> I'm still not sure what would be the proper way to map pipelines (or any GstObject) with spans here. I can think of two options:

I think storing a `Span` with `G(st)Object` somehow would be pretty much ideal from the implementation quality perspective. At the very least then the lifetime of the spans would be naturally tied to the lifetime of the objects these spans are tied to. We can still add some neat API to actually manipulate that information in a discoverable and straightforward fashion.

> We'd still need to walk the parents with my solution (modulo some caching maybe). How would you get rid of that?

So `tracing` spans already have an ability to reference a parent span, so *that* mechanism could be used to track container relationships. Of course, I imagine, it would be pretty hard to keep this in formation in sync with any potential reparenting happening on the GStreamer side, so perhaps just walking the list of parents on the GStreamer side is still better (in that we don’t need to think about these issues at all.)

**Comment by gdesmott** [comment]
> We can still add some neat API to actually manipulate that information in a discoverable and straightforward fashion.

Ok, let's keep the data for now then. I opened https://github.com/standard-ai/tracing-gstreamer/pull/18 with my WIP work.
I does not contain the extra API but that can be easily added later.

> so perhaps just walking the list of parents on the GStreamer side is still better

I think so. Having a single span associated with the "closest" object in the gstreamer hierarchy is good enough IMHO.
